-- MySQL Script generated by MySQL Workbench
-- 10/23/14 00:53:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Administrador_restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Administrador_restaurant` (
  `idAdministrador_restaurant` INT NOT NULL AUTO_INCREMENT,
  `Adm_nombre` VARCHAR(45) NOT NULL,
  `Adm_apellidoPaterno` VARCHAR(45) NULL,
  `Adm_apellidoMatenro` VARCHAR(45) NULL,
  `Adm-rut` VARCHAR(45) NOT NULL,
  `Adm_email` VARCHAR(45) NOT NULL,
  `Adm_direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdministrador_restaurant`),
  UNIQUE INDEX `idAdministrador_restaurant_UNIQUE` (`idAdministrador_restaurant` ASC),
  UNIQUE INDEX `Adm-rut_UNIQUE` (`Adm-rut` ASC),
  UNIQUE INDEX `Adm_email_UNIQUE` (`Adm_email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Restaurant` (
  `idRestaurant` INT NOT NULL AUTO_INCREMENT,
  `Rest_nombre` VARCHAR(45) NOT NULL,
  `Rest_tipo` VARCHAR(45) NOT NULL,
  `Rest_descripcion` VARCHAR(400) NOT NULL,
  `Rest_caracteristicas` VARCHAR(400) NOT NULL,
  `Rest_email` VARCHAR(45) NOT NULL,
  `Rest_direccion` VARCHAR(45) NOT NULL,
  `Administrador_restaurant_idAdministrador_restaurant` INT NOT NULL,
  PRIMARY KEY (`idRestaurant`),
  INDEX `fk_Restaurant_Administrador_restaurant_idx` (`Administrador_restaurant_idAdministrador_restaurant` ASC),
  UNIQUE INDEX `idRestaurant_UNIQUE` (`idRestaurant` ASC),
  UNIQUE INDEX `Rest_nombre_UNIQUE` (`Rest_nombre` ASC),
  UNIQUE INDEX `Rest_email_UNIQUE` (`Rest_email` ASC),
  CONSTRAINT `fk_Restaurant_Administrador_restaurant`
    FOREIGN KEY (`Administrador_restaurant_idAdministrador_restaurant`)
    REFERENCES `mydb`.`Administrador_restaurant` (`idAdministrador_restaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mesa` (
  `Nro_mesa` INT NOT NULL AUTO_INCREMENT,
  `Mesa_fecha` DATE NOT NULL,
  `Mesa_hora` TIME NOT NULL,
  `Mesa_cantPersonas` INT NOT NULL,
  `Restaurant_idRestaurant` INT NOT NULL,
  PRIMARY KEY (`Nro_mesa`),
  INDEX `fk_Mesa_Restaurant1_idx` (`Restaurant_idRestaurant` ASC),
  CONSTRAINT `fk_Mesa_Restaurant1`
    FOREIGN KEY (`Restaurant_idRestaurant`)
    REFERENCES `mydb`.`Restaurant` (`idRestaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Cliente_nombre` VARCHAR(45) NOT NULL,
  `Cliente_apellidoPaterno` VARCHAR(45) NOT NULL,
  `Cliente_apellidoMaterno` VARCHAR(45) NOT NULL,
  `Cliente_rut` VARCHAR(45) NOT NULL,
  `Cliente_email` VARCHAR(45) NOT NULL,
  `Cliente_direccion` VARCHAR(400) NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `Cliente_rut_UNIQUE` (`Cliente_rut` ASC),
  UNIQUE INDEX `Cliente_email_UNIQUE` (`Cliente_email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reserva` (
  `idReserva` INT NOT NULL AUTO_INCREMENT,
  `Reserva_fecha` DATE NOT NULL,
  `Reserva_hora` TIME NOT NULL,
  `Reserva_cantPersonas` INT NOT NULL,
  `Mesa_Nro_mesa` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idReserva`),
  INDEX `fk_Reserva_Mesa1_idx` (`Mesa_Nro_mesa` ASC),
  INDEX `fk_Reserva_Cliente1_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_Reserva_Mesa1`
    FOREIGN KEY (`Mesa_Nro_mesa`)
    REFERENCES `mydb`.`Mesa` (`Nro_mesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Platos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Platos` (
  `idPlatos` INT NOT NULL AUTO_INCREMENT,
  `Platos_nombre` VARCHAR(45) NOT NULL,
  `Platos_descripcion` VARCHAR(45) NULL,
  `Platos_precio` INT NOT NULL,
  `Restaurant_idRestaurant` INT NOT NULL,
  PRIMARY KEY (`idPlatos`),
  INDEX `fk_Platos_Restaurant1_idx` (`Restaurant_idRestaurant` ASC),
  CONSTRAINT `fk_Platos_Restaurant1`
    FOREIGN KEY (`Restaurant_idRestaurant`)
    REFERENCES `mydb`.`Restaurant` (`idRestaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bebidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bebidas` (
  `idBebidas` INT NOT NULL AUTO_INCREMENT,
  `Bebidas_nombre` VARCHAR(45) NOT NULL,
  `Bebidas_descripcion` VARCHAR(45) NULL,
  `Bebidas_precio` INT NOT NULL,
  `Restaurant_idRestaurant` INT NOT NULL,
  PRIMARY KEY (`idBebidas`),
  INDEX `fk_Bebidas_Restaurant1_idx` (`Restaurant_idRestaurant` ASC),
  CONSTRAINT `fk_Bebidas_Restaurant1`
    FOREIGN KEY (`Restaurant_idRestaurant`)
    REFERENCES `mydb`.`Restaurant` (`idRestaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ensaladas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ensaladas` (
  `idEnsaladas` INT NOT NULL AUTO_INCREMENT,
  `Ensaladas_nombre` VARCHAR(45) NOT NULL,
  `Ensaladas_descripcion` VARCHAR(45) NULL,
  `Ensaladas_precio` INT NOT NULL,
  `Restaurant_idRestaurant` INT NOT NULL,
  PRIMARY KEY (`idEnsaladas`),
  INDEX `fk_Ensaladas_Restaurant1_idx` (`Restaurant_idRestaurant` ASC),
  CONSTRAINT `fk_Ensaladas_Restaurant1`
    FOREIGN KEY (`Restaurant_idRestaurant`)
    REFERENCES `mydb`.`Restaurant` (`idRestaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
